name: ♾️ Gemini Batch Prompt Runner (HITL Ready)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'prompts/*.mdx'
      - 'python/sheikh.py'

jobs:
  generate:
    name: 🧠 Gemini Prompt Loop
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3.6.0

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4.9.1
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai python-dotenv

      - name: 🌀 Process All Prompts
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          mkdir -p output
          for file in prompts/*.mdx; do
            filename=$(basename -- "$file")
            name="${filename%.*}"
            echo "🧾 Processing $filename..."
            cat "$file" | python python/sheikh.py > "output/$name.txt"
          done

      - name: 👁️ Human-in-the-Loop Review (Pre-upload)
        run: |
          echo "🧠 Outputs generated. Review in ./output/"
          ls -lah output/
          head -n 20 output/*.txt || true  # show preview

      - name: ☁️ Upload All Outputs
        uses: actions/upload-artifact@v3.1.3
        with:
          name: gemini-all-outputs
          path: output/
