name: Generate Gemini Content

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "prompts/sheikh.mdx"
      - "python/sheikh.py"

jobs:
  generate:
    name: 🧠 Run Gemini Prompt
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: ⚙️ Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai python-dotenv

      - name: 📤 Copy MDX to stdin-friendly file
        run: |
          mkdir -p output
          cat prompts/sheikh.mdx | python python/sheikh.py > output/output.txt
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: 📜 View Generated Output
        run: cat output/output.txt

      - name: 📦 Upload Output Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gemini-output-${{ github.sha }}
          path: output/output.txt
